(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},r="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function t(a,b){if(b){var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}}function ba(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
t("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=ba(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});t("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ba(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var l=0;l<f&&c<e;)if(d[c++]!=b[l++])return!1;return l>=f}});
function ca(){ca=function(){};r.Symbol||(r.Symbol=da)}function ea(a,b){this.b=a;q(this,"description",{configurable:!0,writable:!0,value:b})}ea.prototype.toString=function(){return this.b};var da=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ea("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function u(){ca();var a=r.Symbol.iterator;a||(a=r.Symbol.iterator=r.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}});u=function(){}}function fa(a){u();a={next:a};a[r.Symbol.iterator]=function(){return this};return a}function v(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var ha="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)v(d,e)&&(a[e]=d[e])}return a};t("Object.assign",function(a){return a||ha});
t("WeakMap",function(a){function b(g){this.b=(h+=Math.random()+1).toString();if(g){g=p(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(g){var k=typeof g;return"object"===k&&null!==g||"function"===k}function e(g){if(!v(g,l)){var k=new c;q(g,l,{value:k})}}function f(g){var k=Object[g];k&&(Object[g]=function(m){if(m instanceof c)return m;e(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),m=new a([[g,2],[k,
3]]);if(2!=m.get(g)||3!=m.get(k))return!1;m.delete(g);m.set(k,4);return!m.has(g)&&4==m.get(k)}catch(w){return!1}}())return a;var l="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(g,k){if(!d(g))throw Error("Invalid WeakMap key");e(g);if(!v(g,l))throw Error("WeakMap key fail: "+g);g[l][this.b]=k;return this};b.prototype.get=function(g){return d(g)&&v(g,l)?g[l][this.b]:void 0};b.prototype.has=function(g){return d(g)&&v(g,l)&&v(g[l],this.b)};
b.prototype.delete=function(g){return d(g)&&v(g,l)&&v(g[l],this.b)?delete g[l][this.b]:!1};return b});
t("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,g){var k=h.b;return fa(function(){if(k){for(;k.head!=h.b;)k=k.previous;for(;k.next!=k.head;)return k=k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})}function d(h,g){var k=g&&typeof g;"object"==k||"function"==k?f.has(g)?k=f.get(g):(k=""+ ++l,f.set(g,k)):k="p_"+g;var m=h.c[k];if(m&&v(h.c,k))for(h=0;h<m.length;h++){var w=m[h];if(g!==g&&w.key!==w.key||g===w.key)return{id:k,list:m,index:h,h:w}}return{id:k,
list:m,index:-1,h:void 0}}function e(h){this.c={};this.b=b();this.size=0;if(h){h=p(h);for(var g;!(g=h.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),g=new a(p([[h,"s"]]));if("s"!=g.get(h)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var k=g.entries(),m=k.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!k.next().done?!1:!0}catch(w){return!1}}())return a;u();var f=new WeakMap;e.prototype.set=function(h,g){h=0===h?0:h;var k=d(this,h);k.list||(k.list=this.c[k.id]=[]);k.h?k.h.value=g:(k.h={next:this.b,previous:this.b.previous,head:this.b,key:h,value:g},k.list.push(k.h),this.b.previous.next=k.h,this.b.previous=k.h,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.h&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.c[h.id],h.h.previous.next=h.h.next,
h.h.next.previous=h.h.previous,h.h.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.c={};this.b=this.b.previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).h};e.prototype.get=function(h){return(h=d(this,h).h)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,
g){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,h.call(g,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var l=0;return e});
t("Set",function(a){function b(c){this.b=new Map;if(c){c=p(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.b.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(p([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||
f.value[1]!=f.value[0]?!1:e.next().done}catch(l){return!1}}())return a;u();b.prototype.add=function(c){c=0===c?0:c;this.b.set(c,c);this.size=this.b.size;return this};b.prototype.delete=function(c){c=this.b.delete(c);this.size=this.b.size;return c};b.prototype.clear=function(){this.b.clear();this.size=0};b.prototype.has=function(c){return this.b.has(c)};b.prototype.entries=function(){return this.b.entries()};b.prototype.values=function(){return this.b.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.b.forEach(function(f){return c.call(d,f,f,e)})};return b});t("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==ba(this,b,"includes").indexOf(b,c||0)}});var x=this||self;
function ia(a,b){a=a.split(".");var c=x;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function ja(a){a=a.split(".");for(var b=x,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}
function y(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var ka=Date.now||function(){return+new Date};var la=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},z=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ma=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,
b,c)}:function(a,b,c){var d=c;z(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d};function na(a){return Array.prototype.concat.apply([],arguments)}function oa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function pa(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e=d,f=y(e);if("array"==f||"object"==f&&"number"==typeof e.length){e=a.length||0;f=d.length||0;a.length=e+f;for(var l=0;l<f;l++)a[e+l]=d[l]}else a.push(d)}};function qa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function sa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ra.length;f++)c=ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function A(a,b){this.f=a===ta&&b||"";this.g=ua}A.prototype.c=!0;A.prototype.b=function(){return this.f};function va(a){return a instanceof A&&a.constructor===A&&a.g===ua?a.f:"type_error:Const"}var ua={},ta={};function B(a,b){this.f=a===wa&&b||"";this.g=xa}B.prototype.c=!0;B.prototype.b=function(){return this.f.toString()};function ya(a){if(a instanceof B&&a.constructor===B&&a.g===xa)return a.f;y(a);return"type_error:TrustedResourceUrl"}var xa={},wa={};var za=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Aa(){var a=C,b="";-1!=C.indexOf("Windows")?(b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0"):-1!=C.indexOf("iPhone")&&-1==C.indexOf("iPod")&&-1==C.indexOf("iPad")||-1!=C.indexOf("iPad")||-1!=C.indexOf("iPod")?(b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".")):-1!=C.indexOf("Macintosh")?(b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10"):-1!=C.toLowerCase().indexOf("kaios")?(b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1]):-1!=C.indexOf("Android")?
(b=/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1]):-1!=C.indexOf("CrOS")&&(b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1]);a=0;b=za(String(b||"")).split(".");for(var c=za("2.5").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var f=b[e]||"",l=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==f[0].length&&0==l[0].length)break;a=Ba(0==f[1].length?0:parseInt(f[1],10),0==l[1].length?0:parseInt(l[1],10))||Ba(0==f[2].length,
0==l[2].length)||Ba(f[2],l[2]);f=f[3];l=l[3]}while(0==a)}return a}function Ba(a,b){return a<b?-1:a>b?1:0};function D(a,b){this.f=a===Ca&&b||"";this.g=Da}D.prototype.c=!0;D.prototype.b=function(){return this.f.toString()};function Ea(a){if(a instanceof D&&a.constructor===D&&a.g===Da)return a.f;y(a);return"type_error:SafeUrl"}var Fa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Da={},Ca={};var C;a:{var Ga=x.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){C=Ha;break a}}C=""};function Ia(){this.f=""}Ia.prototype.c=!0;Ia.prototype.b=function(){return this.f.toString()};function E(a){var b=new Ia;b.f=a;return b}E("<!DOCTYPE html>");E("");E("<br>");function Ja(a,b,c){a instanceof D||a instanceof D||(a="object"==typeof a&&a.c?a.b():String(a),Fa.test(a)||(a="about:invalid#zClosurez"),a=new D(Ca,a));(b||x).open(Ea(a),c?va(c):"",void 0,void 0)};function Ka(a){return decodeURIComponent(a.replace(/\+/g," "))}function La(a){return Array.prototype.join.call(arguments,"")};var F=window;function Ma(a){var b=ja("window.location.href");null==a&&(a='Unknown Error of type "null/undefined"');if("string"===typeof a)return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||x.$googDebugFname||b}catch(f){e="Not available",c=!0}return!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name?a:(b=a.message,null==b&&(a.constructor&&
a.constructor instanceof Function?(a.constructor.name?b=a.constructor.name:(b=a.constructor,G[b]?b=G[b]:(b=String(b),G[b]||(c=/function\s+([^\(]+)/m.exec(b),G[b]=c?c[1]:"[Anonymous]"),b=G[b])),b='Unknown Error of type "'+b+'"'):b="Unknown Error of unknown type"),{message:b,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:a.stack||"Not available"})}var G={};function H(a,b){this.width=a;this.height=b}H.prototype.aspectRatio=function(){return this.width/this.height};H.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};H.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};H.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Na(){var a=document;var b="IFRAME";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};var Oa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function I(a){return a.match(Oa)}function J(a){return a?decodeURI(a):a}function Pa(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?Ka(e):"")}}}
function Qa(a,b,c){if("array"==y(b))for(var d=0;d<b.length;d++)Qa(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}function Ra(a){var b=[],c;for(c in a)Qa(c,a[c],b);return b.join("&")};function Sa(a){var b=Ta;if(b)for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&a.call(void 0,b[c],c,b)}function Ua(){var a=[];Sa(function(b){a.push(b)});return a}
var Ta={D:"allow-forms",F:"allow-modals",G:"allow-orientation-lock",H:"allow-pointer-lock",I:"allow-popups",J:"allow-popups-to-escape-sandbox",K:"allow-presentation",L:"allow-same-origin",M:"allow-scripts",N:"allow-top-navigation",O:"allow-top-navigation-by-user-activation"},Va=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return Ua()});function Wa(){var a=Na(),b={};z(Va(),function(c){a.sandbox&&a.sandbox.supports&&a.sandbox.supports(c)&&(b[c]=!0)});return b};var Xa=(new Date).getTime();function Ya(a,b){this.c={};this.b=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof Ya)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}n=Ya.prototype;n.u=function(){Za(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.c[this.b[b]]);return a};n.s=function(){Za(this);return this.b.concat()};
n.clear=function(){this.c={};this.f=this.b.length=0};n.remove=function(a){return K(this.c,a)?(delete this.c[a],this.f--,this.b.length>2*this.f&&Za(this),!0):!1};function Za(a){if(a.f!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];K(a.c,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.f!=a.b.length){var e={};for(c=b=0;b<a.b.length;)d=a.b[b],K(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}}n.get=function(a,b){return K(this.c,a)?this.c[a]:b};
n.set=function(a,b){K(this.c,a)||(this.f++,this.b.push(a));this.c[a]=b};n.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};function K(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function L(a,b){this.c=this.l=this.f="";this.o=null;this.i=this.b="";this.j=!1;var c;a instanceof L?(this.j=void 0!==b?b:a.j,$a(this,a.f),this.l=a.l,ab(this,a.c),bb(this,a.o),this.b=a.b,cb(this,db(a.g)),this.i=a.i):a&&(c=I(String(a)))?(this.j=!!b,$a(this,c[1]||"",!0),this.l=M(c[2]||""),ab(this,c[3]||"",!0),bb(this,c[4]),this.b=M(c[5]||"",!0),cb(this,c[6]||"",!0),this.i=M(c[7]||"")):(this.j=!!b,this.g=new N(null,this.j))}
L.prototype.toString=function(){var a=[],b=this.f;b&&a.push(O(b,eb,!0),":");var c=this.c;if(c||"file"==b)a.push("//"),(b=this.l)&&a.push(O(b,eb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.b)this.c&&"/"!=c.charAt(0)&&a.push("/"),a.push(O(c,"/"==c.charAt(0)?fb:gb,!0));(c=this.g.toString())&&a.push("?",c);(c=this.i)&&a.push("#",O(c,hb));return a.join("")};
L.prototype.resolve=function(a){var b=new L(this),c=!!a.f;c?$a(b,a.f):c=!!a.l;c?b.l=a.l:c=!!a.c;c?ab(b,a.c):c=null!=a.o;var d=a.b;if(c)bb(b,a.o);else if(c=!!a.b){if("/"!=d.charAt(0))if(this.c&&!this.b)d="/"+d;else{var e=b.b.lastIndexOf("/");-1!=e&&(d=b.b.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],l=0;l<e.length;){var h=e[l++];"."==h?d&&l==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&l==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.b=d:c=""!==a.g.toString();c?cb(b,db(a.g)):c=!!a.i;c&&(b.i=a.i);return b};function $a(a,b,c){a.f=c?M(b,!0):b;a.f&&(a.f=a.f.replace(/:$/,""));return a}function ab(a,b,c){a.c=c?M(b,!0):b;return a}function bb(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null}function cb(a,b,c){b instanceof N?(a.g=b,ib(a.g,a.j)):(c||(b=O(b,jb)),a.g=new N(b,a.j))}
function kb(a){return a instanceof L?new L(a):new L(a,void 0)}function M(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function O(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,lb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function lb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var eb=/[#\/\?@]/g,gb=/[#\?:]/g,fb=/[#\?]/g,jb=/[#\?@]/g,hb=/#/g;function N(a,b){this.c=this.b=null;this.f=a||null;this.g=!!b}
function P(a){a.b||(a.b=new Ya,a.c=0,a.f&&Pa(a.f,function(b,c){a.add(Ka(b),c)}))}n=N.prototype;n.add=function(a,b){P(this);this.f=null;a=Q(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.c+=1;return this};n.remove=function(a){P(this);a=Q(this,a);return K(this.b.c,a)?(this.f=null,this.c-=this.b.get(a).length,this.b.remove(a)):!1};n.clear=function(){this.b=this.f=null;this.c=0};function mb(a,b){P(a);b=Q(a,b);return K(a.b.c,b)}
n.forEach=function(a,b){P(this);this.b.forEach(function(c,d){z(c,function(e){a.call(b,e,d,this)},this)},this)};n.s=function(){P(this);for(var a=this.b.u(),b=this.b.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};n.u=function(a){P(this);var b=[];if("string"===typeof a)mb(this,a)&&(b=na(b,this.b.get(Q(this,a))));else{a=this.b.u();for(var c=0;c<a.length;c++)b=na(b,a[c])}return b};
n.set=function(a,b){P(this);this.f=null;a=Q(this,a);mb(this,a)&&(this.c-=this.b.get(a).length);this.b.set(a,[b]);this.c+=1;return this};n.get=function(a,b){if(!a)return b;a=this.u(a);return 0<a.length?String(a[0]):b};n.toString=function(){if(this.f)return this.f;if(!this.b)return"";for(var a=[],b=this.b.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.u(d);for(var f=0;f<d.length;f++){var l=e;""!==d[f]&&(l+="="+encodeURIComponent(String(d[f])));a.push(l)}}return this.f=a.join("&")};
function db(a){var b=new N;b.f=a.f;a.b&&(b.b=new Ya(a.b),b.c=a.c);return b}function Q(a,b){b=String(b);a.g&&(b=b.toLowerCase());return b}function ib(a,b){b&&!a.g&&(P(a),a.f=null,a.b.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),this.remove(e),0<c.length&&(this.f=null,this.b.set(Q(this,e),oa(c)),this.c+=c.length))},a));a.g=b};function nb(){this.c=[];this.b=-1}nb.prototype.set=function(a,b){b=void 0===b?!0:b;0<=a&&52>a&&0===a%1&&this.c[a]!=b&&(this.c[a]=b,this.b=-1)};nb.prototype.get=function(a){return!!this.c[a]};function ob(a){-1==a.b&&(a.b=ma(a.c,function(b,c,d){return c?b+Math.pow(2,d):b},0));return a.b};var R=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};ia("yt.config_",R);function pb(a){var b=arguments;1<b.length?R[b[0]]=b[1]:1===b.length&&Object.assign(R,b[0])}function S(a,b){return a in R?R[a]:b};var qb=[];function rb(a){qb.forEach(function(b){return b(a)})}function sb(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){tb(b),rb(b)}}:a}function tb(a){var b=ja("yt.logging.errors.log");b?b(a,void 0,void 0,void 0,void 0):(b=S("ERRORS",[]),b.push([a,void 0,void 0,void 0,void 0]),pb("ERRORS",b))};function ub(a){var b=[];qa(a,function(c,d){var e=encodeURIComponent(String(d)),f;"array"==y(c)?f=c:f=[c];z(f,function(l){""==l?b.push(e):b.push(e+"="+encodeURIComponent(String(l)))})});return b.join("&")}
function vb(a){"?"==a.charAt(0)&&(a=a.substr(1));a=a.split("&");for(var b={},c=0,d=a.length;c<d;c++){var e=a[c].split("=");if(1==e.length&&e[0]||2==e.length)try{var f=Ka(e[0]||""),l=Ka(e[1]||"");f in b?"array"==y(b[f])?pa(b[f],l):b[f]=[b[f],l]:b[f]=l}catch(g){if("q"!=e[0]){var h=Error("Error decoding URL component");h.c={key:e[0],value:e[1]};tb(h)}}}return b}
function wb(a,b,c){var d=a.split("#",2);a=d[0];d=1<d.length?"#"+d[1]:"";var e=a.split("?",2);a=e[0];e=vb(e[1]||"");for(var f in b)!c&&null!==e&&f in e||(e[f]=b[f]);b=a;a=Ra(e);a?(c=b.indexOf("#"),0>c&&(c=b.length),f=b.indexOf("?"),0>f||f>c?(f=c,e=""):e=b.substring(f+1,c),b=[b.substr(0,f),e,b.substr(c)],c=b[1],b[1]=a?c?c+"&"+a:a:c,a=b[0]+(b[1]?"?"+b[1]:"")+b[2]):a=b;return a+d};function xb(a){var b=yb;a=void 0===a?ja("yt.ads.biscotti.lastId_")||"":a;b=Object.assign(zb(b),Ab(b));b.ca_type="image";a&&(b.bid=a);return b}
function zb(a){var b={};b.dt=Xa;b.flash="0";a:{try{var c=a.b.top.location.href}catch(f){a=2;break a}a=c?c===a.c.location.href?0:1:2}b=(b.frm=a,b);b.u_tz=-(new Date).getTimezoneOffset();var d=void 0===d?F:d;try{var e=d.history.length}catch(f){e=0}b.u_his=e;b.u_java=!!F.navigator&&"unknown"!==typeof F.navigator.javaEnabled&&!!F.navigator.javaEnabled&&F.navigator.javaEnabled();F.screen&&(b.u_h=F.screen.height,b.u_w=F.screen.width,b.u_ah=F.screen.availHeight,b.u_aw=F.screen.availWidth,b.u_cd=F.screen.colorDepth);
F.navigator&&F.navigator.plugins&&(b.u_nplug=F.navigator.plugins.length);F.navigator&&F.navigator.mimeTypes&&(b.u_nmime=F.navigator.mimeTypes.length);return b}
function Ab(a){var b=a.b;try{var c=b.screenX;var d=b.screenY}catch(w){}try{var e=b.outerWidth;var f=b.outerHeight}catch(w){}try{var l=b.innerWidth;var h=b.innerHeight}catch(w){}b=[b.screenLeft,b.screenTop,c,d,b.screen?b.screen.availWidth:void 0,b.screen?b.screen.availTop:void 0,e,f,l,h];c=a.b.top;try{var g=(c||window).document,k="CSS1Compat"==g.compatMode?g.documentElement:g.body;var m=(new H(k.clientWidth,k.clientHeight)).round()}catch(w){m=new H(-12245933,-12245933)}g=m;m={};k=new nb;x.SVGElement&&
x.document.createElementNS&&k.set(0);c=Wa();c["allow-top-navigation-by-user-activation"]&&k.set(1);c["allow-popups-to-escape-sandbox"]&&k.set(2);x.crypto&&x.crypto.subtle&&k.set(3);x.TextDecoder&&x.TextEncoder&&k.set(4);k=ob(k);m.bc=k;m.bih=g.height;m.biw=g.width;m.brdim=b.join();a=a.c;return m.vis={visible:1,hidden:2,prerender:3,preview:4,unloaded:5}[a.visibilityState||a.webkitVisibilityState||a.mozVisibilityState||""]||0,m.wgl=!!F.WebGLRenderingContext,m}
var yb=new function(){var a=window.document;this.b=window;this.c=a};ia("yt.ads_.signals_.getAdSignalsString",function(a){return ub(xb(a))});ka();function Bb(a){var b=S("EXPERIMENTS_FORCED_FLAGS",{});a=void 0!==b[a]?b[a]:S("EXPERIMENT_FLAGS",{})[a];return"string"===typeof a&&"false"===a?!1:!!a};var Cb=void 0!==XMLHttpRequest?function(){return new XMLHttpRequest}:void 0!==ActiveXObject?function(){return new ActiveXObject("Microsoft.XMLHTTP")}:null;function Db(){if(!Cb)return null;var a=Cb();return"open"in a?a:null};function Eb(a,b){"function"==y(a)&&(a=sb(a));return window.setTimeout(a,b)};var Fb={Authorization:"AUTHORIZATION","X-Goog-Visitor-Id":"SANDBOXED_VISITOR_ID","X-YouTube-Client-Name":"INNERTUBE_CONTEXT_CLIENT_NAME","X-YouTube-Client-Version":"INNERTUBE_CONTEXT_CLIENT_VERSION","X-YouTube-Device":"DEVICE","X-Youtube-Identity-Token":"ID_TOKEN","X-YouTube-Page-CL":"PAGE_CL","X-YouTube-Page-Label":"PAGE_BUILD_LABEL","X-YouTube-Variants-Checksum":"VARIANTS_CHECKSUM"},Gb="app debugcss debugjs expflag force_ad_params force_viral_ad_response_params forced_experiments innertube_snapshots innertube_goldens internalcountrycode internalipoverride absolute_experiments conditional_experiments sbb sr_bns_address".split(" "),
Hb=!1;
function Ib(a,b){b=void 0===b?{}:b;if(!c)var c=window.location.href;var d=I(a)[1]||null,e=J(I(a)[3]||null);d&&e?(d=c,c=I(a),d=I(d),c=c[3]==d[3]&&c[1]==d[1]&&c[4]==d[4]):c=e?J(I(c)[3]||null)==e&&(Number(I(c)[4]||null)||null)==(Number(I(a)[4]||null)||null):!0;d=Bb("web_ajax_ignore_global_headers_if_set");for(var f in Fb)e=S(Fb[f]),!e||!c&&!Jb(a,f)||d&&void 0!==b[f]||(b[f]=e);if(c||Jb(a,"X-YouTube-Utc-Offset"))b["X-YouTube-Utc-Offset"]=String(-(new Date).getTimezoneOffset());(c||Jb(a,"X-YouTube-Time-Zone"))&&(f=
"undefined"!=typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)&&(b["X-YouTube-Time-Zone"]=f);if(c||Jb(a,"X-YouTube-Ad-Signals"))b["X-YouTube-Ad-Signals"]=ub(xb(void 0));return b}function Kb(a){var b=window.location.search,c=J(I(a)[3]||null),d=J(I(a)[5]||null);d=(c=c&&(c.endsWith("youtube.com")||c.endsWith("youtube-nocookie.com")))&&d&&d.startsWith("/api/");if(!c||d)return a;var e=vb(b),f={};z(Gb,function(l){e[l]&&(f[l]=e[l])});return wb(a,f||{},!1)}
function Jb(a,b){var c=S("CORS_HEADER_WHITELIST")||{};a=J(I(a)[3]||null);return a?(c=c[a])?0<=la(c,b):!1:!0}
function Lb(a){var b=S("ECATCHER_REPORT_HOST","")+"/error_204",c=a.format||"JSON";b=Mb(b,a);var d=Nb(b,a),e=!1,f,l=Ob(b,function(h){if(!e){e=!0;f&&window.clearTimeout(f);a:switch(h&&"status"in h?h.status:-1){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 304:var g=!0;break a;default:g=!1}var k=null,m=400<=h.status&&500>h.status,w=500<=h.status&&600>h.status;if(g||m||w)k=Pb(c,h,a.P);if(g)a:if(h&&204==h.status)g=!0;else{switch(c){case "XML":g=0==parseInt(k&&k.return_code,10);break a;
case "RAW":g=!0;break a}g=!!k}k=k||{};m=a.context||x;g?a.w&&a.w.call(m,h,k):a.onError&&a.onError.call(m,h,k);a.v&&a.v.call(m,h,k)}},a.method,d,a.headers,a.responseType,a.withCredentials);a.A&&0<a.timeout&&(f=Eb(function(){e||(e=!0,l.abort(),window.clearTimeout(f),a.A.call(a.context||x,l))},a.timeout))}
function Mb(a,b){b.S&&(a=document.location.protocol+"//"+document.location.hostname+(document.location.port?":"+document.location.port:"")+a);var c=S("XSRF_FIELD_NAME",void 0);if(b=b.C)b[c]&&delete b[c],a=wb(a,b||{},!0);return a}
function Nb(a,b){var c=S("XSRF_FIELD_NAME",void 0),d=S("XSRF_TOKEN",void 0),e=b.T||"",f=b.m,l=S("XSRF_FIELD_NAME",void 0),h;b.headers&&(h=b.headers["Content-Type"]);b.R||J(I(a)[3]||null)&&!b.withCredentials&&J(I(a)[3]||null)!=document.location.hostname||"POST"!=b.method||h&&"application/x-www-form-urlencoded"!=h||b.m&&b.m[l]||(f||(f={}),f[c]=d);f&&"string"===typeof e&&(e=vb(e),sa(e,f),e=b.B&&"JSON"==b.B?JSON.stringify(e):Ra(e));if(!(a=e)&&(a=f)){a:{for(var g in f){f=!1;break a}f=!0}a=!f}!Hb&&a&&"POST"!=
b.method&&(Hb=!0,tb(Error("AJAX request with postData should use POST")));return e}function Pb(a,b,c){var d=null;switch(a){case "JSON":a=b.responseText;b=b.getResponseHeader("Content-Type")||"";a&&0<=b.indexOf("json")&&(d=JSON.parse(a));break;case "XML":if(b=(b=b.responseXML)?Qb(b):null)d={},z(b.getElementsByTagName("*"),function(e){d[e.tagName]=Rb(e)})}c&&Sb(d);return d}
function Sb(a){var b=typeof a;if("object"==b&&null!=a||"function"==b)for(var c in a)if((b="html_content"==c)||(b=c.length-5,b=0<=b&&c.indexOf("_html",b)==b),b){b=c;var d=E(a[c]);a[b]=d}else Sb(a[c])}function Qb(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null}function Rb(a){var b="";z(a.childNodes,function(c){b+=c.nodeValue});return b}
function Ob(a,b,c,d,e,f,l){function h(){4==(g&&"readyState"in g?g.readyState:0)&&b&&sb(b)(g)}c=void 0===c?"GET":c;d=void 0===d?"":d;var g=Db();if(!g)return null;"onloadend"in g?g.addEventListener("loadend",h,!1):g.onreadystatechange=h;Bb("debug_forward_web_query_parameters")&&(a=Kb(a));g.open(c,a,!0);f&&(g.responseType=f);l&&(g.withCredentials=!0);c="POST"==c&&(void 0===window.FormData||!(d instanceof FormData));if(e=Ib(a,e))for(var k in e)g.setRequestHeader(k,e[k]),"content-type"==k.toLowerCase()&&
(c=!1);c&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g.send(d);return g};var Tb=new Set,Ub=0;function Vb(a,b,c,d){c+="."+a;a=String(JSON.stringify(b)).substr(0,500);d[c]=a;return c.length+a.length};function Wb(a,b){var c=void 0===b?"ERROR":b;b=Xb;var d=void 0;d=void 0===d?{}:d;d.name="KAIOS_LAUNCHER";d.version=b||S("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0);b=d||{};c=void 0===c?"ERROR":c;c=void 0===c?"ERROR":c;d=window&&window.yterr||!1;if(a&&d&&!(5<=Ub)){Bb("console_log_js_exceptions")&&(d=[],d.push("Name: "+a.name),d.push("Message: "+a.message),a.hasOwnProperty("params")&&d.push("Error Params: "+JSON.stringify(a.c)),d.push("File name: "+a.fileName),d.push("Stacktrace: "+a.stack),window.console.log(d.join("\n"),
a));d=a.g;var e=a.f;if(a.b&&a.b.length)for(var f=0,l=0;l<a.b.length;l++){var h=a.b[l],g="params."+l;f+=g.length;if(h)if(Array.isArray(h))for(var k=b,m=0;m<h.length&&!(h[m]&&(f+=Vb(m,h[m],g,k),500<f));m++);else if("object"===typeof h)for(k in k=void 0,m=b,h){if(h[k]&&(f+=Vb(k,h[k],g,m),500<f))break}else b[g]=String(JSON.stringify(h)).substring(0,500),f+=b[g].length;else b[g]=String(JSON.stringify(h)).substring(0,500),f+=b[g].length;if(500<=f)break}else if(a.hasOwnProperty("params"))if(h=a.params,"object"===
typeof a.params)for(l in g=0,h){if(h[l]&&(f="params."+l,k=String(JSON.stringify(h[l])).substr(0,500),b[f]=k,g+=f.length+k.length,500<g))break}else b.params=String(JSON.stringify(h)).substr(0,500);a=Ma(a);(d=d||a.stack)||(d="Not available");l=a.lineNumber.toString();isNaN(l)||!e||isNaN(e)||(l=l+":"+e);window.yterr&&"function"==y(window.yterr)&&window.yterr(a);if(!(Tb.has(a.message)||0<=d.indexOf("/YouTubeCenter.js")||0<=d.indexOf("/mytube.js"))){c={C:{a:"logerror",t:"jserror",type:a.name,msg:a.message.substr(0,
250),line:l,level:c,"client.name":b.name},m:{url:S("PAGE_NAME",window.location.href),file:a.fileName},method:"POST"};b.version&&(c["client.version"]=b.version);if(c.m){d&&(c.m.stack=d);d=p(Object.keys(b));for(e=d.next();!e.done;e=d.next())e=e.value,c.m["client."+e]=b[e];if(b=S("LATEST_ECATCHER_SERVICE_TRACKING_PARAMS",void 0))for(d=p(Object.keys(b)),e=d.next();!e.done;e=d.next())e=e.value,c.m[e]=b[e]}Lb(c);Tb.add(a.message);Ub++}}};var Yb=new B(wa,va(new A(ta,"https://m.youtube.com/?client=kaios"))),Zb=(new URL("https://m.youtube.com/?client=kaios")).origin,$b=["youtube.com","m.youtube.com","www.youtube.com","youtu.be"];function ac(){if(0<=Aa())return!1;setTimeout(function(){Ja("https://m.youtube.com/?client=kaios",void 0,new A(ta,"_blank"));window.close()},3E4);return!0};var Xb="",T=1,bc="none",cc=null;function dc(){var a=ec.bind(null,"YouTube ");navigator.mozApps.getSelf().then(function(b){Xb=b.manifest.version||"";a(Xb)})};var U={context:{dialServer:null,remoteControl:null,isUsbConnected:!1}};function fc(){U.context.dialServer=null;U.context.remoteControl=null}function gc(){innopia.dial.search({type:"rndis",timeout:5E3,success:hc,fail:ic})}function jc(a){(U.context.isUsbConnected=a.isConnected)?U.context.remoteControl||gc():window.applicationApi.showMweb()}var kc=!1;function lc(){kc||(kc=!0,setInterval(function(){window.navigator.dongleManager.dongleStatus||1===T||window.applicationApi.showMweb()},2E3))}
function hc(a){U.context.dialServer=a;window.setTimeout(function(){U.context.remoteControl?window.applicationApi.showRemote():mc()},1E3)}function ic(){fc();gc()}function mc(){innopia.rcu.connect({changestatus:nc,fail:oc,server:U.context.dialServer,success:pc})}function qc(){null!=U.context.remoteControl&&(U.context.remoteControl.disconnect(),U.context.remoteControl=null)}function pc(a,b){null!=b&&(U.context.remoteControl=b,window.applicationApi.showRemote())}
function oc(a,b){b&&"not_supported"===b.error?Ja("https://support.google.com/youtube/answer/9219067"):gc()}function nc(a){null!=U.context.remoteControl&&("DISCONNECTED"===a?(qc(),mc()):"FINISH_YOUTUBE"===a&&(qc(),window.applicationApi.showMweb()))};var rc=null;function V(){if(!rc){var a=document;a.querySelectorAll&&a.querySelector?a=a.querySelector("IFRAME"):(a.querySelectorAll&&a.querySelector?a=a.querySelectorAll("IFRAME"):a=a.getElementsByTagName("IFRAME"),a=a[0]||null);rc=a}return rc}function W(a){V().contentWindow.postMessage(a,"*")};function sc(a){a&&a.classList.add("hidden")}function tc(a){a&&a.classList.remove("hidden")};var X={expectActivity:uc,showError:vc,showMweb:wc,showRemote:xc};function wc(a){a=void 0===a?!1:a;fc();window.navigator.spatialNavigationEnabled=!0;a||(V().src=ya(Yb).toString());T=1;tc(document.getElementById("mweb-container"));sc(document.getElementById("remote"))}function xc(){window.navigator.spatialNavigationEnabled=!1;V().src="";T=2;sc(document.getElementById("mweb-container"));tc(document.getElementById("remote"));V().blur()}
function vc(a){var b=document.getElementById("error");tc(b);a.forEach(function(c){var d=document.createElement("div");d.innerText=c;b.appendChild(d)})}function uc(){return x.location.href.includes("expect_activity=1")};function yc(a){document.getElementById("arrow-"+a).classList.add("active");document.getElementById("arrow-"+a+"-panel").classList.add("active");window.setTimeout(function(){document.getElementById("arrow-"+a).classList.remove("active");document.getElementById("arrow-"+a+"-panel").classList.remove("active")},300)}function zc(){document.getElementById("center-ok").classList.add("active");window.setTimeout(function(){document.getElementById("center-ok").classList.remove("active")},300)};function Y(a){Wb(Error(a),"WARNING")};function Ac(a){if("3"===a||"r"===a||"VolumeUp"===a)return navigator.volumeManager.requestUp(),!0;if("1"===a||"w"===a||"VolumeDown"===a)return navigator.volumeManager.requestDown(),!0;if("Backspace"===a||"EndCall"===a){if(document.fullscreenElement)document.exitFullscreen();else{a=V();var b=a.getCanGoBack();b.onsuccess=Bc.bind(null,a,b)}return!0}return Cc(a)?!0:!1}
function Bc(a,b){b.result?a.goBack():0===cc?new MozActivity({name:"voice-assistant",data:{from:"YouTubeExit"}}):W({showExitConfirmation:!0})}
function Cc(a){

if(document.fullscreenElement||"none"!==bc){
if(screen.orientation.type.startsWith("landscape")&&0!==screen.orientation.angle||"landscape"===bc&&screen.orientation.type.startsWith("portrait-primary")){

// dpad keys

if("ArrowDown"===a||"8"===a)return W({seekForward:!0}),!0;

if("ArrowUp"===a||"2"===a)return W({seekBackward:!0}),!0}
else
{
if("ArrowRight"===a||"6"===a)return W({seekForward:!0}),!0;

if("ArrowLeft"===a||"4"===a)return W({seekBackward:!0}),!0}

if("Enter"===a||"5"===a)

return W({pauseOrPlay:!0}),
!0}return!1};

var Z=null;
function Dc(){Z&&clearInterval(Z);var a=120;Z=setInterval(function(){W({register:!0});a--;0>=a&&Z&&clearInterval(Z)},250)}function Ec(a){var b=a.origin;(b===Zb||b.endsWith(".youtube.com"))&&a.data&&(Z&&clearInterval(Z),a.data.keypress?Ac(a.data.keypress):a.data.exit?window.close():a.data.enableCursor?window.navigator.spatialNavigationEnabled=!0:a.data.enableDpad?window.navigator.spatialNavigationEnabled=!1:a.data.setFauxFullscreenOrientation&&(bc=a.data.setFauxFullscreenOrientation))}
function Fc(){Dc();V().blur()}function Gc(){V().focus()};function Hc(){document.fullscreenElement?screen.orientation.unlock():screen.orientation.lock("natural")}function Ic(a){document.fullscreenElement||(screen.orientation.lock("portrait"),a.preventDefault(),a.stopPropagation())};var Jc=null;function ec(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];Jc&&clearTimeout(Jc);var d=document.getElementById("toast");d&&(d.textContent=La.apply(null,b),tc(d),Jc=setTimeout(function(){sc(d);Jc=null},3E3))};var Kc=null;

function Lc(a){2===T&&U.context.remoteControl&&("ArrowUp"===a.key?(yc("up"),U.context.remoteControl.key_Up()):"ArrowRight"===a.key?(yc("right"),U.context.remoteControl.key_Right()):"ArrowLeft"===a.key?(yc("left"),U.context.remoteControl.key_Left()):"ArrowDown"===a.key?(yc("down"),U.context.remoteControl.key_Down()):"Enter"===a.key?(zc(),U.context.remoteControl.key_Enter()):"SoftRight"===a.key?(U.context.remoteControl.key_Exit(),window.applicationApi.showMweb()):"SoftLeft"===a.key?window.close():"Backspace"===
a.key&&(U.context.remoteControl.key_Back(),a.preventDefault()))}function Mc(a){1===T&&Ac(a.key)&&(a.preventDefault(),a.stopPropagation())}function Nc(){if(1===T){var a=V();document.activeElement!==a&&a.focus()}}
function Oc(a){Kc&&(clearTimeout(Kc),Kc=null);if("YouTube"!==a.source.name)X.showMweb(),Y("Invalid MozActivityRequestHandler provided: "+JSON.stringify(a.source)+".");else if(2===T)Y("Received MozActivityRequestHandler while in REMOTE mode.");else{switch(a.source.data.source){case "assistant":cc=0;break;default:cc=1}switch(a.source.data.type){case "url":a=a.source.data.url;var b;if(b=!!a){b=V();var c=kb(a);if(0<=la($b,c.c)){c.g.set("feature","deeplink");var d=kb(Zb);c=$a(ab(c,d.c),d.f).toString();
b.src=ya(new B(wa,c)).toString();b=!0}else b=!1}X.showMweb(b);b||Y("Invalid URL provided in MozActivityRequestHandler: "+a+".");break;case "video":X.showMweb();break;default:X.showMweb(),Y("Unsupported MozActivityRequestHandler provided: "+JSON.stringify(a.source)+".")}}};pb("ECATCHER_REPORT_HOST","https://www.youtube.com");window.addEventListener("error",function(a){Wb(a.error,"ERROR")});
window.addEventListener("DOMContentLoaded",function(){ac()?(X.showError(["This app won't work without a system update. Please go to Settings > Device > Software Update.","Redirecting to the browser in 30 seconds."]),Y("Application is not supported on current platform. About to redirect to Browser.")):(dc(),X.expectActivity()?Kc=setTimeout(X.showMweb,5E3):X.showMweb(),document.addEventListener("keydown",Lc,!0),document.addEventListener("keypress",Mc,!0),document.addEventListener("focus",Nc,!0),document.addEventListener("fullscreenchange",
Hc,!0),screen.orientation.onchange=Ic,window.addEventListener("message",Ec),V().addEventListener("mozbrowserloadstart",Fc),V().addEventListener("mozbrowserloadend",Gc),ia("Context",U.context),gc(),lc(),window.navigator.dongleManager.ondonglestatuschange=jc,window.applicationApi=X,window.navigator.mozSetMessageHandler("activity",Oc))});}).call(this);
